--[[
    DungeonFormer - Core configuration and static data.
    Class colors, dungeon list, zones, and default settings.
]]

DungeonFormer = DungeonFormer or {}
local DF = DungeonFormer

DF.ClassColors = {
    CustomColor = { r = 0.77, g = 0.12, b = 0.23, a = 1 },
    DeathKnight = { r = 0.77, g = 0.12, b = 0.23 },
    Druid = { r = 1.00, g = 0.49, b = 0.04 },
    Hunter = { r = 0.67, g = 0.83, b = 0.45 },
    Mage = { r = 0.41, g = 0.80, b = 0.94 },
    Monk = { r = 0, g = 1, b = 0.59 },
    Paladin = { r = 0.96, g = 0.55, b = 0.73 },
    Priest = { r = 1.00, g = 1.00, b = 1.00 },
    Rogue = { r = 1.00, g = 0.96, b = 0.41 },
    Shaman = { r = 0.0, g = 0.44, b = 0.87 },
    Warlock = { r = 0.58, g = 0.51, b = 0.79 },
    Warrior = { r = 0.78, g = 0.61, b = 0.43 },
}

DF.Dungeons = {
    { name = "Choose A Dungeon", low = 1, high = 10, sname = "a dungeon" },
    { name = "[13-18] Ragefire Chasm - Orgrimar", low = 13, high = 18, sname = "Ragefire Chasm" },
    { name = "[17-24] Wailing Caverns - The Barrens", low = 17, high = 24, sname = "Wailing Caverns" },
    { name = "[17-26] The Deadmines - Westfall", low = 17, high = 26, sname = "The Deadmines" },
    { name = "[22-30] Shadowfang Keep - Silverpine Forest", low = 22, high = 30, sname = "Shadowfang Keep" },
    { name = "[24-32] Blackfathom Deeps - Ashenvale", low = 24, high = 32, sname = "Blackfathom Deeps" },
    { name = "[24-32] The Stockade - Stormwind", low = 24, high = 32, sname = "The Stockade" },
    { name = "[29-38] Gnomeregan - Dun Morogh", low = 29, high = 38, sname = "Gnomeregan" },
    { name = "[29-38] Razorfen Kraul - The Barrens", low = 29, high = 38, sname = "Razorfen Kraul" },
    { name = "[26-36] SM Graveyard - Tirisfal Glades", low = 26, high = 36, sname = "SM Graveyard" },
    { name = "[29-39] SM Library - Tirisfal Glades", low = 29, high = 39, sname = "SM Library" },
    { name = "[32-42] SM Armory - Tirisfal Glades", low = 32, high = 42, sname = "SM Armory" },
    { name = "[35-45] SM Cathedral - Tirisfal Glades", low = 35, high = 45, sname = "SM Cathedral" },
    { name = "[37-46] Razorfen Downs - Thousand Needles", low = 37, high = 46, sname = "Razorfen Downs" },
    { name = "[41-51] Uldaman - Badlands", low = 41, high = 51, sname = "Uldaman" },
    { name = "[42-46] Zul'Farrak - Tanaris", low = 42, high = 56, sname = "Zul'Farrak" },
    { name = "[46-55] Maraudon - Desolace", low = 46, high = 55, sname = "Maraudon" },
    { name = "[50-56] Sunken Temple - Swamp of Sorrows", low = 50, high = 56, sname = "Sunken Temple" },
    { name = "[52-60] BRD - Burning Steppes", low = 52, high = 60, sname = "Blackrock Depths" },
    { name = "[55-60] LBRS - Burning Steppes", low = 55, high = 60, sname = "L Blackrock Spire" },
    { name = "[55-60] UBRS - Burning Steppes", low = 55, high = 60, sname = "U Blackrock Spire" },
    { name = "[55-60] DM East - Feralas", low = 55, high = 60, sname = "Dire Maul East" },
    { name = "[55-60] DM West - Feralas", low = 55, high = 60, sname = "Dire Maul West" },
    { name = "[55-60] DM North - Feralas", low = 55, high = 60, sname = "Dire Maul North" },
    { name = "[58-60] Scholomance - W Plaguelands", low = 58, high = 60, sname = "Scholomance" },
    { name = "[58-60] Stratholme - E Plaguelands", low = 58, high = 60, sname = "Stratholme" },
}

DF.Zones = {
    "All Zones",
    "Alterac Mountains",
    "Arathi Highlands",
    "Ashenvale",
    "Azshara",
    "Badlands",
    "Blackrock Mountain",
    "Blackrock Spire",
    "Blasted Lands",
    "Burning Steppes",
    "Caverns of Time",
    "Darkshore",
    "Darnassus",
    "Deadwind Pass",
    "Deeprun Tram",
    "Desolace",
    "Dun Morogh",
    "Durotar",
    "Duskwood",
    "Dustwallow Marsh",
    "Eastern Plaguelands",
    "Elwynn Forest",
    "Felwood",
    "Feralas",
    "Hillsbrad Foothills",
    "Ironforge",
    "Loch Modan",
    "Moonglade",
    "Mulgore",
    "Onyxia's Lair",
    "Orgrimmar",
    "Redridge Mountains",
    "Searing Gorge",
    "Silithus",
    "Silverpine Forest",
    "Stonetalon Mountains",
    "Stormwind City",
    "Stranglethorn Vale",
    "Swamp of Sorrows",
    "Tanaris",
    "Teldrassil",
    "The Barrens",
    "The Hinterlands",
    "Thousand Needles",
    "Thunder Bluff",
    "Tirisfal Glades",
    "Un'Goro Crater",
    "Undercity",
    "Western Plaguelands",
    "Westfall",
    "Wetlands",
    "Winterspring",
}
